### ISSUE TITLE
Employment Combined - National - Daily.csv - file missing 2 weeks data

### ISSUE THREAD

**Issue by recessionalert** [OpportunityInsights/EconomicTracker#10]
The Employment Combined - National - Daily.csv has data only until 24/09 despite being updated 2 days ago. In fact the file has less data in it than its previous version which had data until 4 october.

**Comment by eugeneolkhov** [comment]
Similar issue with the Employment Combined - County - Daily.csv. Appears to only have data through Sept 3rd, while a previous download had through Oct.

**Comment by michaelstepner** [comment]
> The Employment Combined - National - Daily.csv has data only until 24/09 despite being updated 2 days ago. In fact the file has less data in it than its previous version which had data until 4 october.

Hi @recessionalert,

Thanks for getting in touch, and apologies that it's taken us a long time to catch up on these GH Issues reports.

We replicated this on our end, and confirmed your observation about `Employment Combined - National - Daily.csv`:
* The file posted on October 10 contained (projected) data up until October 4.
* The file posted on October 20 contained (projected) data up until September 24.

The change arose due to an adjustment in our prediction for employment. As background, we construct our employment series using paycheck deposits; since there is a delay between date of work and date of paycheck being deposited, this means that there is a lag between the last date on which we observe paycheck deposits and the last date on which we can calculate employment. To reduce this lag, we use timesheet data from Kronos and data on paycheck data on workers paid on weekly paycycles (as opposed to bi-weekly, monthly etc. paycycles) to "predict" employment. (Details of this step are contained in our [data documentation](https://github.com/OpportunityInsights/EconomicTracker/blob/main/docs/oi_tracker_data_documentation.md).)

In the October 10 update, the last date for realized employment was August 21. In the October 20 update, the last date was September 3. The change came in the prediction step -- we moved from using Kronos data alone to predict employment, to using Paychex and Kronos data to predict employment. Because we wanted to be conservative when switching to a new prediction approach, we chose only to predict employment for three weeks after the last realized value, which is a shorter prediction window than we were previously using. This led to the change that you noted. We do not anticipate further changes to the prediction method.

**Comment by michaelstepner** [comment]
> Similar issue with the Employment Combined - County - Daily.csv. Appears to only have data through Sept 3rd, while a previous download had through Oct.

Hi @eugeneolkhov,

Thanks for letting us know, and like I mentioned in my previous comment, apologies that it's taken a while to get back to you.

We looked into it but we haven't been able to replicate the issue you noted. The `Employment Combined - County - Daily.csv` file was updated twice in October prior to your comment: once on October 10, and again on October 20:

* The file posted on Octuber 10 contained data up to August 21.
* The file posted on October 20 contained data up to September 3.

Is it possible that the data you noted extending through October was the national-level data, rather than the county-level data? The national-level data predicts employment using timesheet data and paycheck data from workers with weekly paycycles; as discussed in my previous post. For this reason, the national-level data for October 10 did extend into October, whereas the county-level data did not.
