### ISSUE TITLE
Removal of Affinity daily data

### ISSUE THREAD

**Issue by c3-robertyoung** [OpportunityInsights/EconomicTracker#5]
I see that in a recent [commit](https://github.com/OpportunityInsights/EconomicTracker/commit/0f82e0ec350d4a4b14c633119b7080b3f8ed5848) the daily Affinity spending data was removed. Was this intentional, and will this data be brought back?

**Comment by michaelstepner** [comment]
Hi Robert,

The underlying data we receive from Affinity has switched from daily to weekly, so we are providing weekly data starting this week and going forward. We may be able to obtain daily data extracts again in the future, although there are no concrete plans right now to do so.

In the meantime, all the daily data we have published in the past is available in the archives of the Git repository.

**Comment by mwaugh0328** [comment]
Sorry to bring this up again, but (i) the website (https://tracktherecovery.org/) makes it look like the data is daily (thought the series has become noticeably more smoother, since July), and (ii) the repo still says "..County%20-%20Daily.csv" for example suggesting that the data is daily. 

What I think is going on that it is weekly, but is being smoothed/extrapolated in some way down to the daily frequency? Is this in the paper/documentation somewhere?

**Comment by michaelstepner** [comment]
Hi Mike,

The data is daily through July 4th 2020, and presented as a 7 day lookback moving average. Beginning July 5th 2020, the data is weekly and presented as weekly data points with a linear interpolation between each weekly point.

We do anticipate getting new refreshes of daily data, which we'll add to the data when we get them. We'll keep the documentation up to date here:
https://github.com/OpportunityInsights/EconomicTracker/blob/main/docs/oi_tracker_data_documentation.md#consumer-spending
